### ISSUE TITLE
Work with crates?

### ISSUE THREAD

**Issue by Yevgnen** [rnag/cargo-rx#19]
#### Is your feature request related to a problem? Please describe.

Some libraries like [tract](https://github.com/sonos/tract) and [axum](https://github.com/tokio-rs/axum) use workspaces to indicate examples, but current `cargo-rx` does not seem to able to identify them.

#### Describe the solution you'd like
Identify workspaces for examples based on directory names?

#### Additional context
No.

**Comment by rnag** [comment]
Thanks again for opening this issue!

From an initial look, it looks like `axum` for example suggests running the workspace examples using [cargo run](https://github.com/tokio-rs/axum/blob/main/examples/stream-to-file/src/main.rs#L4) instead of `cargo run --example`.

I agree that this is a good use case for this project, since `cargo` doesn't identify such examples currently, but it would be nice to fuzzy find and select a workspace example to run. The one caveat is that we'll need to leverage `cargo run` instead of `cargo run --example` to test out such examples.

In terms of changes required in this project, I think the simplest way would be to keep a separate list (or hashset) of workspace-specific examples -- note that we could probably determine such examples based on the presence of a `Cargo.toml` file in an examples/ subfolder. Then, based on the example that the user selects, we can then proceed to load the `Cargo.toml` of the example (in order to retrieve the package name, though I think `cd` and just `cargo run` could also work) and run the workspace example without passing the `--example` argument to `cargo run`.

**Comment by rnag** [comment]
Hi @Yevgnen, I've been looking into this recently, and just a note that the terminology  *workspaces* might not be the exact use case here -- I believe that this use case is actually to support Cargo crates with [binary targets].

A few additional notes for clarification:

- The Cargo crates would be nested (as sub-folders) within the `examples/` folder
- Each crate would contain its own `Cargo.toml` file
- The crate would be run with `cargo run` and the default binary target would then be `src/main.rs`
- For multiple binaries, we would define entries for `[[bin]]` in the `Cargo.toml` file, and then `cargo-rx` should display each binary target as a separate example to run.

Hope this helps. I'm underway with the new release to support this feature request, and it should be rolling out shortly.

[binary targets]: https://doc.rust-lang.org/cargo/reference/cargo-targets.html#binaries

**Comment by rnag** [comment]
@Yevgnen This feature request has been accepted and should be available as part of `v0.3.0`. [Here](https://github.com/rnag/cargo-rx/releases/tag/v0.3.0) are the release notes.

I have tested so far with the `axum` project after cloning it locally, and the good news is that binary targets for all crates within the `examples/` folder are now correctly detected by the `rx` tool as expected.

With projects such as `tract`, some binaries and examples (mainly indirect examples, such as those within workspace members) are detected by `cargo` but not by `rx` as of yet. I have noted this issue as a separate feature request, as part of #21 which I have opened.

Cheers, and have a great Monday! 🎉
